# Finding eigenvalues of a matrix by QR method

In [44]:
from numpy import *
S = array([[10,2j,3+2j],[-2j,1,3],[3-2j,3,1]],dtype=complex)

def f(A):
    A , orthonormal_basis = array(A,dtype=float),[]
    for i in range(len(A)):
        a = A[i]
        for j in range(len(orthonormal_basis)):
            a -= dot(A[i],orthonormal_basis[j])*orthonormal_basis[j]
        ao = a/linalg.norm(a)
        orthonormal_basis.append(ao) 
    return transpose(orthonormal_basis) 

def QR(A):
    Z = [A[:,i] for i in range(len(A))]
    Q,Q_t = f(Z),transpose(f(Z))
    R = dot(Q_t,A)
    return Q,R

Q,R = QR(S)
print('Q:','\n',Q.round(2),'\n','\n','R:','\n',R.round(1),'\n','\n','QR:','\n',dot(Q,R).round(2),'\n','\n','S:','\n',S,'\n')
for i in range(0,1000):
    Q,R = QR(S)
    A1 = dot(R,Q)
    S = A1
    
print('The eigenvalues of matrix S are:','\n',diag(S).reshape(len(S),1))



D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  """


Q: 
 [[ 0.96 -0.27  0.09]
 [-0.    0.33  0.94]
 [ 0.29  0.9  -0.31]] 
 
 R: 
 [[10.4-0.6j  0.9+1.9j  3.2+1.9j]
 [ 0. -2.5j  3. -0.5j  1.1-0.5j]
 [ 0. -1.3j  0. +0.2j  2.8+0.2j]] 
 
 QR: 
 [[10.-0.j  0.+2.j  3.+2.j]
 [ 0.-2.j  1.+0.j  3.+0.j]
 [ 3.-2.j  3.-0.j  1.-0.j]] 
 
 S: 
 [[10.+0.j  0.+2.j  3.+2.j]
 [-0.-2.j  1.+0.j  3.+0.j]
 [ 3.-2.j  3.+0.j  1.+0.j]] 

The eigenvalues of matrix S are: 
 [[10.99017622-4.33649354e-18j]
 [ 3.39508097+2.75629675e-17j]
 [-2.38525719-3.78430010e-17j]]


# Finding eigenvalues of a matrix by Gram Schmidt

In [45]:
from numpy import *
S = array([[19,-1,-2,2,0.5],[-1,5,-1,-2,1],[-2,-1,2,-1,5],[2,-2,-1,3,0.1],[50,-1,-2,2,2]],dtype=float)

def f(A):
    A , orthonormal_basis = array(A,dtype=float),[]
    for i in range(len(A)):
        a = A[i]
        for j in range(len(orthonormal_basis)):
            a -= dot(A[i],orthonormal_basis[j])*orthonormal_basis[j]
        ao = a/linalg.norm(a)
        orthonormal_basis.append(ao) 
    return transpose(orthonormal_basis) 

def QR(A):
    Z = [A[:,i] for i in range(len(A))]
    Q,Q_t = f(Z),transpose(f(Z))
    R = dot(Q_t,A)
    return Q,R 

Q,R = QR(S)
print('Q:','\n',Q.round(2),'\n','\n','R:','\n',R.round(1),'\n','\n','QR:','\n',dot(Q,R).round(2),'\n','\n','S:','\n',S,'\n')
for i in range(0,1000):
    Q,R = QR(S)
    A1 = dot(R,Q)
    S = A1
    
print('The eigenvalues of matrix S are:','\n',diag(S).reshape(len(S),1))








Q: 
 [[ 0.35 -0.09 -0.46 -0.38  0.71]
 [-0.02  0.91 -0.1   0.33  0.23]
 [-0.04 -0.19  0.7   0.31  0.61]
 [ 0.04 -0.36 -0.49  0.79  0.05]
 [ 0.93  0.06  0.22  0.13 -0.24]] 
 
 R: 
 [[53.6 -1.4 -2.7  2.8  1.8]
 [-0.   5.5 -0.9 -2.8 -0. ]
 [-0.  -0.   2.5 -2.4  3.6]
 [-0.   0.  -0.   0.9  2. ]
 [ 0.  -0.   0.   0.   3.2]] 
 
 QR: 
 [[19.  -1.  -2.   2.   0.5]
 [-1.   5.  -1.  -2.   1. ]
 [-2.  -1.   2.  -1.   5. ]
 [ 2.  -2.  -1.   3.   0.1]
 [50.  -1.  -2.   2.   2. ]] 
 
 S: 
 [[19.  -1.  -2.   2.   0.5]
 [-1.   5.  -1.  -2.   1. ]
 [-2.  -1.   2.  -1.   5. ]
 [ 2.  -2.  -1.   3.   0.1]
 [50.  -1.  -2.   2.   2. ]] 

The eigenvalues of matrix S are: 
 [[19.12428569]
 [ 7.30349304]
 [ 5.9498826 ]
 [-2.41663392]
 [ 1.03897261]]


# Finding eigenvalues of a matrix by Householder Method

In [5]:
from numpy import *
a = array([[19,-1,-2,2,0.5],[-1,5,-1,-2,1],[-2,-1,2,-1,5],[2,-2,-1,3,0.1],[50,-1,-2,2,2]],dtype=float)
print('A= ','\n',a.round(2),'\n')
n = len(a)
I = identity(n)
x = a[0:n,0]
x,xp = x.reshape(len(x),1),zeros([len(x),1])
xp[0] = linalg.norm(x)
u,iden = x - xp,identity(len(x))
h = iden - (2*dot(u,transpose(u)))/(dot(transpose(u),u))
a,H = dot(h,a),array([h])
m = H[0]

for i in range(1,n-1):
    x = a[i:n,i]
    x = x.reshape(len(x),1)
    xp = zeros([len(x),1])
    xp[0] = linalg.norm(x)
    u = x - xp
    iden = identity(len(x))
    h = iden - (2*dot(u,transpose(u)))/(dot(transpose(u),u))
    I = identity(n)
    I[i:n,i:n] = h
    h = I
    H = concatenate((H,[h]))
    a = dot(h,a)

for i in range(1,n-1):
    m = dot(H[i],m)       # H3.H2.H1.H0 = (Q)^-1
Q,R = linalg.inv(m),a

print('R= ','\n',R.round(1),'\n','\n','Q= ','\n',Q.round(2),'\n','\n','QR= ','\n',dot(Q,R),'\n','\n')

A=  
 [[19.  -1.  -2.   2.   0.5]
 [-1.   5.  -1.  -2.   1. ]
 [-2.  -1.   2.  -1.   5. ]
 [ 2.  -2.  -1.   3.   0.1]
 [50.  -1.  -2.   2.   2. ]] 

R=  
 [[53.6 -1.4 -2.7  2.8  1.8]
 [-0.   5.5 -0.9 -2.8 -0. ]
 [-0.   0.   2.5 -2.4  3.6]
 [-0.   0.   0.   0.9  2. ]
 [-0.  -0.   0.   0.  -3.2]] 
 
 Q=  
 [[ 0.35 -0.09 -0.46 -0.38 -0.71]
 [-0.02  0.91 -0.1   0.33 -0.23]
 [-0.04 -0.19  0.7   0.31 -0.61]
 [ 0.04 -0.36 -0.49  0.79 -0.05]
 [ 0.93  0.06  0.22  0.13  0.24]] 
 
 QR=  
 [[19.  -1.  -2.   2.   0.5]
 [-1.   5.  -1.  -2.   1. ]
 [-2.  -1.   2.  -1.   5. ]
 [ 2.  -2.  -1.   3.   0.1]
 [50.  -1.  -2.   2.   2. ]] 
 



## Does QR method works for any N x N matrix ?

The major limitation of the QR algorithm is that already the first stage generates usually complete fill-in in general sparse matrices. It can therefore not be applied to large sparse matrices, simply because of excessive memory requirements.
This method is not recommended in the case where only eigenvalues are desired of a symmetric tridiagonal matrix. Also, I think this method can't be used for non-diagonalizable matrices


## Limitations:

Usually, many steps are required to have convergence; certainly much more than n. In fact, the basic QR-method can be arbitrarily slow if the eigenvalues are close to each other. It is often slow in practice. Householder reflection algorithm is bandwidth heavy and not parallelizable, as every reflection that produces a new zero element changes the entirety of both Q and R matrices. The reduction of a sparse matrix to tridiagonal or Hessenberg form produces fill-in, thus destroying the sparsity structure which one almost always tries to preserve.