# **INVERSE OF A MATRIX**

In [1]:
from pylab import *
from numpy import *

a = array([ [1.,1.,1.] , [1.,-1.,1.] , [2.,-1.,3.] ])
b = array([ [1.,0.,0.] , [0.,1.,0.] , [0.,0.,1.] ])
n = 3

'To make lower traingular matrix'        
for k in range(0,n-1):
    for i in range(k+1,n):
        c = ( a[i][k]/a[k][k] )
        for j in range(0,n):
            a[i][j] -= c*( a[k][j] )
            b[i][j] -= c*( b[k][j] )
            
'To make upper traingular matrix'
for k in range(n-1,0,-1):  
    for i in range(k-1,-1,-1):    
        c = ( a[i][k]/a[k][k] )
        for j in range(0,n): 
            a[i][j] -= c*( a[k][j] )
            b[i][j] -= c*( b[k][j] )
            
'To make identity Matrix and find inverse matrix'
for i in range(0,n):
    c = a[i][i]
    for j in range(0,n):
        a[i][j] =  a[i][j]/c
        b[i][j] =  b[i][j]/c
        
a = array([ [1.,1.,1.] , [1.,-1.,1.] , [2.,-1.,3.] ])       
print('THE INVERSE OF MATRIX' ,'\n', f'{a}','\n','\n','IS','\n','\n',b)   

        
    
    

THE INVERSE OF MATRIX 
 [[ 1.  1.  1.]
 [ 1. -1.  1.]
 [ 2. -1.  3.]] 
 
 IS 
 
 [[ 1.   2.  -1. ]
 [ 0.5 -0.5 -0. ]
 [-0.5 -1.5  1. ]]
