# Row reduction of a matrix by Gauss Elimination method

In [1]:
from pylab import *
from numpy import *

a = array([ [1.,1.,1.] , [1.,-1.,1.] , [2.,-1.,3.] ])
b = array([ [6.],[2.],[9.] ])
n = 3

for k in range(0,n-1):
    for i in range(k+1,n):
        c = ( a[i][k]/a[k][k] )
        b[i] -= c*( b[k] )
        for j in range(0,n):
            a[i][j] -= c*( a[k][j] )

print(a)
print(b)

X = array([ 0.,0.,0. ])

for i in range(n-1,-1,-1):
    X[i] = (( b[i] )/( a[i][i] ))
    for j in range(0,n):
        if(i!=j):
            X[i] -= ((a[i][j]*X[j])/(a[i][i]))
print(X)

[[ 1.  1.  1.]
 [ 0. -2.  0.]
 [ 0.  0.  1.]]
[[ 6.]
 [-4.]
 [ 3.]]
[1. 2. 3.]
